---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "4 20 * * 0"

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Run Docker container.
        run: >
          docker run -d -p 9924:80 --name airgradient \
            -v "$PWD":/var/www/html \
            php:8-apache

      - name: Inspect Docker container.
        run: >
          sleep 3 && docker ps

      - name: Test that we're getting the expected result.
        run: curl http://localhost:9925/metrics | grep "Could not resolve host"
